// Generated by scripts/set-env.js from .env.local — do not edit manually.
export const environment = {
  production: false,
  supabaseUrl: 'http://172.18.12.16:54321',
  supabasePublishableKey: 'sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH',
};
