// Generated by scripts/set-env.js from .env.local — do not edit manually.
export const environment = {
  production: false,
  supabaseUrl: 'https://wvsfuraaeupedatohdnf.supabase.co',
  supabasePublishableKey: 'sb_publishable_T8ZQavdm4hr7VNVrdBjDWQ_2Z38dhRq',
};
