// Reads apps/web/.env.local and generates src/environments/environment.ts.
// Run automatically via `npm start`. Do not run manually for staging/prod builds.

const fs = require('fs');
const path = require('path');

const envFile = path.resolve(__dirname, '../.env.local');
const targetFile = path.resolve(__dirname, '../src/environments/environment.ts');

if (!fs.existsSync(envFile)) {
  console.error(
    '\n[set-env] ERROR: apps/web/.env.local not found.\n' +
      '  Copy apps/web/.env.example to apps/web/.env.local and fill in your values.\n',
  );
  process.exit(1);
}

const env = Object.fromEntries(
  fs
    .readFileSync(envFile, 'utf8')
    .split('\n')
    .filter((l) => l.trim() && !l.trim().startsWith('#'))
    .map((l) => {
      const idx = l.indexOf('=');
      return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()];
    })
    .filter(([k]) => k),
);

const required = ['SUPABASE_URL', 'SUPABASE_PUBLISHABLE_KEY'];
const missing = required.filter((k) => !env[k]);
if (missing.length) {
  console.error(`\n[set-env] ERROR: Missing required keys in .env.local: ${missing.join(', ')}\n`);
  process.exit(1);
}

const content = `// Generated by scripts/set-env.js from .env.local — do not edit manually.
export const environment = {
  production: false,
  supabaseUrl: '${env['SUPABASE_URL']}',
  supabasePublishableKey: '${env['SUPABASE_PUBLISHABLE_KEY']}',
};
`;

fs.writeFileSync(targetFile, content);
console.log('[set-env] environment.ts written from .env.local');
