// Reads apps/web/.env.local (or process.env for Docker) and generates
// src/environments/environment.ts.
// Run automatically via `npm start`. Do not run manually for staging/prod builds.

const fs = require('fs');
const path = require('path');

const envFile = path.resolve(__dirname, '../.env.local');
const targetFile = path.resolve(__dirname, '../src/environments/environment.ts');

let env = {};

if (fs.existsSync(envFile)) {
  // Local development: read from .env.local
  env = Object.fromEntries(
    fs
      .readFileSync(envFile, 'utf8')
      .split('\n')
      .filter((l) => l.trim() && !l.trim().startsWith('#'))
      .map((l) => {
        const idx = l.indexOf('=');
        return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()];
      })
      .filter(([k]) => k),
  );
  console.log('[set-env] reading configuration from .env.local');
} else {
  // Docker / CI: read from process.env
  env = process.env;
  console.log('[set-env] .env.local not found, reading configuration from environment variables');
}

const required = ['SUPABASE_URL', 'SUPABASE_PUBLISHABLE_KEY'];
const missing = required.filter((k) => !env[k]);
if (missing.length) {
  console.error(
    `\n[set-env] ERROR: Missing required variables: ${missing.join(', ')}\n` +
      '  For local development: copy apps/web/.env.example to apps/web/.env.local and fill in your values.\n' +
      '  For Docker: pass them as environment variables, e.g. docker run -e SUPABASE_URL=... -e SUPABASE_PUBLISHABLE_KEY=...\n',
  );
  process.exit(1);
}

const content = `// Generated by scripts/set-env.js — do not edit manually.
export const environment = {
  production: false,
  supabaseUrl: '${env['SUPABASE_URL']}',
  supabasePublishableKey: '${env['SUPABASE_PUBLISHABLE_KEY']}',
};
`;

fs.writeFileSync(targetFile, content);
console.log('[set-env] environment.ts written successfully');
